openapi: 3.0.3
info:
  title: Quiz App Haderach API
  version: '1.0.0'
  description: To initialize and grade a Dune related quiz
servers:
  - url: https://localhost:8080/api/v1
paths:
  /quiz:
    get:
      summary: Query Questions
      description: Initialize quiz with Dune related questions
      operationId: queryQuestions
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
    post:
      summary: Mark Answers
      description: Complete quiz by marking the specified Dune related answers
      operationId: markAnswers
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Answer'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
components:
  schemas:
    Question:
      type: object
      properties:
        question:
          type: string
        options:
          type: array
          items:
            type: string
    Answer:
      type: integer
      format: int32
    Result:
      type: object
      properties:
        mark:
          type: integer
          format: int32
        percentage:
          type: integer
          format: int32
        grade:
          type: string
          enum:
            - Fail
            - Pass
            - Merit
            - Distinction